
server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql:///student_database
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
dubbo:
  application:
    name: user_service
  registry:
    address: zookeeper://49.234.130.191:2181
  protocol:
    port: -1